---
meta:
  name:    kafka-service-broker
  target:  ohio-cf
  url:     https://ci-ohio.starkandwayne.com

  initial_version: 1.0.0

  go:
    version: "1.9"
    cmd_module: (( concat "github.com/" meta.github.owner "/" meta.github.repo "/cmd/broker" ))

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  aws:
    bucket:      (( grab meta.name ))
    access_key:  ((aws-cfcommunity-access))
    secret_key:  ((aws-cfcommunity-secret))

  github:
    owner:  starkandwayne
    repo:   kafka-service-broker
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:  ((slack-webhook))
    username: ((slack-username))
    icon:     ((slack-icon-url))
    channel:  "#bigdata-boshrelease"
