---
meta:
  name: kafka-service-broker
  target: sw
  url: https://ci.starkandwayne.com
  initial_version: 1.0.0

  git:
    email:  drnic+bot@starkandwayne.com
    name:   "Stark & Wayne CI Bot"

  aws:
    bucket: (( grab meta.name ))
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner: starkandwayne
    repo: kafka-service-broker
    private_key:  (( vault "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  slack:
    webhook: IGNORE
    channel: '#bigdata-boshrelease'
    username:      starkandwayne-ci
    icon:          https://www.starkandwayne.com/assets/images/shield-blue-50x50.png
